---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: foundry

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-foundry-vtt
commonLabels:
  app: foundry

resources:
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/services.yaml

images:
  - name: foundry
    newName: ghcr.io/felddy/foundryvtt
    newTag: 13.346.0

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: foundry
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: foundry
      namespace: foundry
      annotations:
        gethomepage.dev/href: https://vtt.crt.lol
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Table Topper
        gethomepage.dev/group: Media
        gethomepage.dev/icon: foundry-vtt
        gethomepage.dev/name: Foundry VTT
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
