---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foundry
  namespace: foundry
spec:
  target:
    name: foundry
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 95cf7d9c-da0f-41ed-b08e-ea5c5cad5970
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: admin-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 95cf7d9c-da0f-41ed-b08e-ea5c5cad5970
        metadataPolicy: None
        property: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: username
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 95cf7d9c-da0f-41ed-b08e-ea5c5cad5970
        metadataPolicy: None
        property: username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
