---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry
  namespace: foundry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-retain
  volumeMode: Filesystem
